---
layout: page
title: "About the Instructor"
permalink: /about
---
  
<link href="css/style.css" rel="stylesheet"></link> 

[Monica Truelove-Hill](https://www.ed.ac.uk/profile/monica-truelove-hill)

<p><a href="mailto:m.truelovehill@ed.ac.uk">m.truelovehill@ed.ac.uk</a></p>


I'm currently a Lecturer in Psychological Research Methods based in the Clinical Psychology department at the University of Edinburgh. I migrated from a fixed-term role in the Psychology department, where they have an [excellent Data Analysis/Research Methods team](https://uoepsy.github.io/). Working with them inspired me to develop and design my own open-access materials, leading to what you see here. 

I recognise that most Psychology students consider statistics to be boring, difficult, and/or anxiety provoking. I love the challenge of presenting these concepts in a way that's engaging and generally accessible to a wide audience. 

When I'm not teaching stats, answering emails, or buried under a pile of marking, I like exploring new places with my family, eating really good food, and hitting things really hard (AKA doing Muay Thai). 

